version: '3'

services:
  srv:
    build:
      context: ./srv
    command: yarn dev
    volumes:
      - ./srv:/usr/src/app
    environment:
     - PORT=3001
    ports:
     - "3001:3001"

  db:
    image: mongo

  rabbitmq:
    image: rabbitmq

  crn:
    build:
      context: ./crn
    command: yarn dev
    volumes:
      - ./crn:/usr/src/app
    environment:
      - PORT=3002
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq

  worker_fetch:
    build:
      context: ./worker_fetch
    command: yarn dev
    environment:
      - "READINGS_DB=mongodb://db/ticnsp-eaas-readings"
      - "JOBS_DB=mongodb://db/ticnsp-eaas-jobs"
      - "LOG_LEVEL=info"
      - "JOB_TODO=fetch"
      - "AMQP_HOST=amqp://rabbitmq"
      - "AMQP_QUEUE=fetch_queue"
    volumes:
      - ./worker_fetch:/usr/src/app
    depends_on:
      - rabbitmq      

  pg:
    image: postgres
    volumes:
      - ./pg/tmp/db:/var/lib/postgresql/data

  webapp:
    build: 
      context: ./webapp
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - "SESSION_KEY=ZWE5MjgxYzVmOWYxOTEwOTc5ODU0MTk0MDEyMTc2OTQxN2I4MmFiYiAgLQo="
      - "TICNSP_PG_HOST=pg"
      - "TICNSP_PG_USER=postgres"
    # date +%s | shasum5.18 | base64 | head -c 128 ; echo
    volumes:
      - ./webapp:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - pg